-- database-setup.sql

CREATE DATABASE `EMPLOYEE_DB` IF NOT EXISTS;

USE `EMPLOYEE_DB`;

CREATE TABLE `EMPLOYEE_DB`.`EMPLOYEES`(
    EMPID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2),
    HIREDATE_DATE DATE
); 

-- INSERT SOME EMPLOYEE DATA
INSERT INTO `EMPLOYEES` (NAME, EMAIL, DEPARTMENT, SALARY, HIRE_DATE) VALUES
('John Doe', 'john.doe@company.com', 'IT', 75000.00, '2023-01-15'),
('Jane Smith', 'jane.smith@company.com', 'HR', 65000.00, '2022-03-20'),
('Bob Johnson', 'bob.johnson@company.com', 'Finance', 80000.00, '2021-11-10');